sources:
  - VirtuaGrotesk.designspace
axisOrder:
  - wght
familyName: "Virtua Grotesk"
outputDir: ../fonts
buildOTF: false
buildWebfont: false
flattenComponents: false
decomposeTransformedComponents: false
