#!/usr/bin/env python3
"""Report current Fontspector WARN results for built fonts."""

from __future__ import annotations

import json
import os
from collections import Counter, defaultdict
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


def fontspector_json(command: list[str], report_path: Path) -> dict:
    if shutil.which("fontspector") is None:
        raise RuntimeError("Missing fontspector. Install https://github.com/fonttools/fontspector and rerun.")

    (Path.home() / ".fontspector").mkdir(exist_ok=True)
    result = subprocess.run(
        command,
        check=False,
        env=os.environ.copy(),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    if result.returncode not in (0, 1):
        raise RuntimeError(f"Fontspector failed with exit code {result.returncode}.")

    try:
        return json.loads(report_path.read_text())
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Fontspector wrote invalid JSON: {exc}") from exc


DEFAULT_FONT_PATHS = [
    Path("fonts/variable/VirtuaGrotesk[wght].ttf"),
    Path("fonts/ttf/VirtuaGrotesk-Regular.ttf"),
    Path("fonts/ttf/VirtuaGrotesk-Medium.ttf"),
    Path("fonts/ttf/VirtuaGrotesk-SemiBold.ttf"),
    Path("fonts/ttf/VirtuaGrotesk-Bold.ttf"),
]
METADATA_WARNING_PROBE = Path("documentation/google-fonts/fontspector-metadata-warning-probe.md")
ZERO_WARNING_WORKLIST = Path("documentation/google-fonts/fontspector-zero-warning-worklist.md")
TRIAGE_NOTES = {
    "contour_count": (
        "drawing/source",
        "Review alongside `documentation/google-fonts/fontspector-contour-count.md`; this is "
        "expected to move as outlines and Arabic forms are completed.",
    ),
    "dotted_circle": (
        "drawing/source",
        "Add U+25CC as part of Arabic mark support.",
    ),
    "googlefonts/metadata/unreachable_subsetting": (
        "downstream metadata",
        "Recheck after final `METADATA.pb` subsets are generated by Packager.",
    ),
    "googlefonts/vendor_id": (
        "user decision",
        "Choose and register a four-character vendor ID, or explicitly defer.",
    ),
    "gpos_kerning_info": (
        "user decision/source",
        "Decide whether kerning is required before the first Google Fonts PR.",
    ),
    "mandatory_avar_table": (
        "user decision",
        "Verify the generated variable font includes the intended identity or non-linear `avar` mapping.",
    ),
    "outline_alignment_miss": (
        "drawing/source",
        "Review while final outlines are cleaned up.",
    ),
    "outline_colinear_vectors": (
        "drawing/source",
        "Review while final outlines are cleaned up.",
    ),
    "outline_direction": (
        "drawing/source",
        "Review contour direction while final outlines are cleaned up.",
    ),
    "outline_semi_vertical": (
        "drawing/source",
        "Review near-horizontal/vertical outlines while final outlines are cleaned up.",
    ),
    "rupee": (
        "drawing/source",
        "Add U+20B9 if the final glyphset still targets Google Fonts coverage.",
    ),
    "soft_dotted": (
        "drawing/source",
        "Add dotless forms/substitution behavior when combining mark support is completed.",
    ),
    "unreachable_glyphs": (
        "source cleanup",
        "Review Arabic helper glyphs and PUA scope after final feature and glyphset decisions.",
    ),
}
DECISION_NOTES = {
    "googlefonts/metadata/unreachable_subsetting": (
        "Downstream metadata review",
        "After Packager generates `METADATA.pb`, confirm Arabic, Latin, menu, "
        "and any PUA/private glyph scope match the final submission.",
        "`documentation/google-fonts/google-fonts-metadata-review.md`",
    ),
    "googlefonts/vendor_id": (
        "Vendor ID",
        "Choose a registered four-character vendor ID, or explicitly defer with "
        "`NONE` for the first submission.",
        "`documentation/google-fonts/google-fonts-decisions.md`",
    ),
    "gpos_kerning_info": (
        "Kerning scope",
        "Decide whether GPOS kerning is required before the first Google Fonts PR.",
        "`documentation/google-fonts/google-fonts-decisions.md`",
    ),
    "mandatory_avar_table": (
        "`avar` strategy",
        "Verify the generated variable font includes the intended identity or "
        "non-linear `avar` mapping.",
        "`documentation/google-fonts/google-fonts-decisions.md`",
    ),
    "unreachable_glyphs": (
        "Reachability and PUA scope",
        "Review Arabic helper glyphs and private-use glyphs after the final "
        "glyphset and feature decisions are made.",
        "`documentation/google-fonts/google-fonts-decisions.md`",
    ),
}


def fontspector_results(font_paths: list[Path]) -> list[dict]:
    with tempfile.NamedTemporaryFile(suffix=".json") as report:
        command = [
            "fontspector",
            "-p",
            "googlefonts",
            *[str(path) for path in font_paths],
            "--exclude-checkid",
            "googlefonts/repo/dirname_matches_nameid_1",
            "--json",
            report.name,
            "--loglevel",
            "error",
            "--skip-network",
        ]
        data = fontspector_json(command, Path(report.name))

    results = []
    for family_results in data["results"].values():
        for checks in family_results.values():
            results.extend(checks)
    return results


def clean_message(message: str) -> str:
    message = re.sub(r"\s+", " ", message).strip()
    return message.replace("|", "\\|")


def warning_rows(results: list[dict]) -> list[str]:
    rows = []
    for result in sorted(results, key=lambda item: item["check_id"]):
        for subresult in result.get("subresults", []):
            if subresult.get("severity") != "WARN":
                continue
            rows.append(
                "| `{}` | `{}` | {} |".format(
                    result["check_id"],
                    subresult.get("code", ""),
                    clean_message(subresult.get("message", "")),
                )
            )
    return rows


def warning_records(results: list[dict]) -> list[tuple[str, str, str, str]]:
    records = []
    for result in results:
        filename = result.get("filename", "")
        check_id = result["check_id"]
        for subresult in result.get("subresults", []):
            if subresult.get("severity") != "WARN":
                continue
            records.append(
                (
                    check_id,
                    subresult.get("code", ""),
                    filename,
                    clean_message(subresult.get("message", "")),
                )
            )
    return records


def summary_rows(records: list[tuple[str, str, str, str]]) -> list[str]:
    by_check: dict[str, list[tuple[str, str, str, str]]] = defaultdict(list)
    for record in records:
        by_check[record[0]].append(record)

    rows = [
        "| Check | Count | Category | Fonts | Triage note |",
        "| --- | ---: | --- | --- | --- |",
    ]
    for check_id in sorted(by_check):
        records_for_check = by_check[check_id]
        fonts = sorted({record[2] for record in records_for_check if record[2]})
        category, note = TRIAGE_NOTES.get(
            check_id,
            ("review", "Review before final Google Fonts submission."),
        )
        rows.append(
            "| `{}` | {} | {} | {} | {} |".format(
                check_id,
                len(records_for_check),
                category,
                "<br>".join(f"`{font}`" for font in fonts),
                note,
            )
        )
    return rows


def code_summary(records: list[tuple[str, str, str, str]]) -> list[str]:
    counts = Counter((check_id, code) for check_id, code, _, _ in records)
    rows = [
        "| Check | Code | Count |",
        "| --- | --- | ---: |",
    ]
    for (check_id, code), count in sorted(counts.items()):
        rows.append(f"| `{check_id}` | `{code}` | {count} |")
    return rows


def first_line_value(pattern: str, text: str, default: str = "unknown") -> str:
    match = re.search(pattern, text, flags=re.MULTILINE)
    return match.group(1).strip() if match else default


def package_warning_floor_lines() -> list[str]:
    probe_path = METADATA_WARNING_PROBE
    zero_path = ZERO_WARNING_WORKLIST
    if not probe_path.exists() or not zero_path.exists():
        return [
            "## Package-Context Warning Floor",
            "",
            (
                "Package-context warning floor: not available. Run "
                "`make metadata-warning-check` and `make zero-warning-check` "
                "after a current build."
            ),
            "",
        ]

    probe_text = probe_path.read_text(encoding="utf-8")
    zero_text = zero_path.read_text(encoding="utf-8")
    baseline_rows = re.findall(
        r"^\| `([^`]+)` \| `([^`]+)` \| (\d+) \|$",
        probe_text,
        flags=re.MULTILINE,
    )
    floor_count = sum(int(count) for _, _, count in baseline_rows)
    floor_checks = ", ".join(f"`{check}`: {count}" for check, _, count in baseline_rows) or "none"
    zero_possible = first_line_value(
        r"^- Honest zero-warning state possible with current scope: (.+)$",
        zero_text,
    )
    preview_subsets = first_line_value(
        r"^- Intended package subsets in preview: (.+)$",
        zero_text,
    )
    latin_missing = first_line_value(
        r"^- GF Latin Core missing codepoints: (.+)$",
        zero_text,
    )
    arabic_missing = first_line_value(
        r"^- GF Arabic Core missing codepoints: (.+)$",
        zero_text,
    )
    unreachable = re.findall(r"^- `(U\+[0-9A-F]{4,6} [^`]+)`$", probe_text, flags=re.MULTILINE)
    lines = [
        "## Package-Context Warning Floor",
        "",
        (
            f"- Package-context warning floor: {floor_count} WARN "
            f"({floor_checks})"
        ),
        f"- Honest zero-warning state possible with current scope: {zero_possible}",
        f"- Intended package subsets in preview: {preview_subsets}",
        f"- GF Latin Core missing codepoints: {latin_missing}",
        f"- GF Arabic Core missing codepoints: {arabic_missing}",
    ]
    if unreachable:
        lines.append(f"- Remaining unreachable support codepoints: {', '.join(f'`{item}`' for item in unreachable)}")
    lines.extend(
        [
            "",
            (
                "Use this package-context floor for downstream triage. The loose-font "
                "count above can repeat the same metadata warning once per generated "
                "binary, including static fonts that are not planned for the first "
                "variable-font package."
            ),
            "",
        ]
    )
    return lines


def decision_rows(records: list[tuple[str, str, str, str]]) -> list[str]:
    by_check: dict[str, list[tuple[str, str, str, str]]] = defaultdict(list)
    for record in records:
        if record[0] in DECISION_NOTES:
            by_check[record[0]].append(record)

    rows = [
        "| Check | Count | Decision area | Action | Record in |",
        "| --- | ---: | --- | --- | --- |",
    ]
    for check_id in sorted(by_check):
        decision_area, action, record_in = DECISION_NOTES[check_id]
        rows.append(
            "| `{}` | {} | {} | {} | {} |".format(
                check_id,
                len(by_check[check_id]),
                decision_area,
                action,
                record_in,
            )
        )
    return rows


def markdown_report(font_paths: list[Path]) -> str:
    results = fontspector_results(font_paths)
    records = warning_records(results)
    rows = warning_rows(results)
    lines = [
        "# Fontspector Warnings",
        "",
        "Fonts:",
        "",
        *[f"- `{path}`" for path in font_paths],
        "",
        f"Warnings: {len(records)}",
        "",
        "These warnings require design, script-scope, or submission-policy review.",
        "For subset and reachability warnings, treat this loose-font report as",
        "directional until the intended downstream `METADATA.pb` is tested in",
        "package context; see `documentation/google-fonts/fontspector-metadata-warning-probe.md`",
        "and `documentation/google-fonts/fontspector-zero-warning-worklist.md`.",
        "",
        *package_warning_floor_lines(),
        "## Triage Summary",
        "",
        *summary_rows(records),
        "",
        "## Decision-Linked Warnings",
        "",
        *decision_rows(records),
        "",
        "## Warning Codes",
        "",
        *code_summary(records),
        "",
        "## Full Warning Messages",
        "",
        "| Check | Code | Message |",
        "| --- | --- | --- |",
    ]
    lines.extend(rows)
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    args = [Path(arg) for arg in argv[1:]]
    if not args:
        font_paths = DEFAULT_FONT_PATHS
        output_path = None
    elif len(args) == 1:
        font_paths = args
        output_path = None
    else:
        font_paths = args[:-1]
        output_path = args[-1]

    try:
        report = markdown_report(font_paths)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report)
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
