"""Scoreboard: the one number that must go up.

Scans both masters and reports Bold-debt burn-down by outline class:

- line-only  : drawable today with the lane-2 transfer tool (font-garden-lab)
- curved     : blocked on curve support (the ampersand milestone)
- composite  : propagates once every base glyph it references is non-red
- mixed/empty: contours+components / no outline

Statuses from Runebender mark colors: green = human-approved, red = debt,
any other mark = draft awaiting grading, none = unmarked (trusted in the
Regular, which is the ground-truth master).

    make scoreboard            print + rewrite documentation/scoreboard.md
    python scripts/scoreboard.py --quiet   print headline only
"""

import datetime
import plistlib
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MASTERS = ['Regular', 'Bold']
GREEN = '0.09,0.72,0.44,1'
RED = '1,0.29,0.24,1'
OUT = ROOT / 'documentation/scoreboard.md'
CLASSES = ['line-only', 'curved', 'composite', 'mixed', 'empty']


def load_master(name):
    gdir = ROOT / f'sources/VirtuaGrotesk-{name}.ufo/glyphs'
    contents = plistlib.load(open(gdir / 'contents.plist', 'rb'))
    glyphs = {}
    for gname, fn in contents.items():
        root = ET.parse(gdir / fn).getroot()
        outline = root.find('outline')
        contours = outline.findall('contour') if outline is not None else []
        components = outline.findall('component') if outline is not None else []
        curved = any(p.get('type') in ('curve', 'qcurve') or p.get('type') is None
                     for c in contours for p in c.findall('point'))
        if contours and components:
            klass = 'mixed'
        elif components:
            klass = 'composite'
        elif not contours:
            klass = 'empty'
        else:
            klass = 'curved' if curved else 'line-only'

        mark = None
        lib = root.find('lib')
        if lib is not None:
            d = lib.find('dict')
            keys = list(d) if d is not None else []
            for i, el in enumerate(keys):
                if el.tag == 'key' and el.text == 'public.markColor':
                    mark = keys[i + 1].text
        status = {GREEN: 'green', RED: 'red', None: 'unmarked'}.get(
            mark, 'draft')
        bases = [c.get('base') for c in components]
        glyphs[gname] = {'class': klass, 'status': status, 'bases': bases}
    return glyphs


def composite_ready(name, glyphs, seen=None):
    """All contour-bearing glyphs this composite (recursively) references
    are non-red."""
    seen = seen or set()
    if name in seen:
        return False
    g = glyphs.get(name)
    if g is None:
        return False
    if g['class'] in ('line-only', 'curved', 'mixed', 'empty'):
        return g['status'] != 'red'
    return all(composite_ready(b, glyphs, seen | {name}) for b in g['bases'])


def main():
    quiet = '--quiet' in sys.argv
    data = {m: load_master(m) for m in MASTERS}
    names = list(data['Regular'])
    total = len(names)

    non_red = {m: sum(1 for g in data[m].values() if g['status'] != 'red')
               for m in MASTERS}
    both = sum(1 for n in names
               if all(data[m][n]['status'] != 'red' for m in MASTERS))

    bold = data['Bold']
    red_by_class = {k: [n for n, g in bold.items()
                        if g['status'] == 'red' and g['class'] == k]
                    for k in CLASSES}
    ready_composites = [n for n in red_by_class['composite']
                        if composite_ready(n, bold)]
    drafts = sorted(n for n, g in bold.items() if g['status'] == 'draft')

    today = datetime.date.today().isoformat()
    headline = (f'GF gate: {both}/{total} glyphs non-red in BOTH masters | '
                f'Regular {non_red["Regular"]}/{total} | '
                f'Bold {non_red["Bold"]}/{total}')
    print(headline)
    if quiet:
        return

    lines = [
        '# Scoreboard',
        '',
        'Generated by `make scoreboard` (`scripts/scoreboard.py`). The',
        'headline is the Google Fonts gate: every glyph non-red in both',
        'masters (see `documentation/google-fonts-readiness.md`).',
        '',
        f'**{headline}**',
        '',
        f'_Last updated: {today}_',
        '',
        '## Bold debt by outline class',
        '',
        '| Class | Red | Unblocked by |',
        '| --- | ---: | --- |',
        f'| line-only | {len(red_by_class["line-only"])} | lane-2 transfer '
        f'tool, works today (`harness/RUNBOOK-bolden.md`) |',
        f'| curved | {len(red_by_class["curved"])} | curve support in the '
        f'transfer tool (ampersand milestone) |',
        f'| composite | {len(red_by_class["composite"])} | bases going '
        f'non-red ({len(ready_composites)} ready to propagate now) |',
        f'| mixed | {len(red_by_class["mixed"])} | case by case |',
        f'| empty | {len(red_by_class["empty"])} | mark green (nothing to '
        f'draw) |',
        '',
        f'## Drafts awaiting human grading ({len(drafts)})',
        '',
        ', '.join(f'`{n}`' for n in drafts) or '(none)',
        '',
        '## Regular debt (fix here first — Bold derives from it)',
        '',
        ', '.join(f'`{n}`' for n, g in sorted(data['Regular'].items())
                  if g['status'] == 'red') or '(none)',
        '',
        '## History',
        '',
        '| Date | Both non-red | Regular | Bold |',
        '| --- | ---: | ---: | ---: |',
    ]

    history = []
    if OUT.exists():
        in_hist = False
        for line in OUT.read_text().splitlines():
            if line.startswith('## History'):
                in_hist = True
            elif in_hist and line.startswith('| 2'):
                history.append(line)
    row = (f'| {today} | {both}/{total} | {non_red["Regular"]}/{total} '
           f'| {non_red["Bold"]}/{total} |')
    if not history or history[-1].split('|')[2:] != row.split('|')[2:]:
        history.append(row)
    else:
        history[-1] = row
    lines += history + ['']

    OUT.write_text('\n'.join(lines))
    print(f'wrote {OUT.relative_to(ROOT)}')
    print(f'  bold red: line-only {len(red_by_class["line-only"])}, '
          f'curved {len(red_by_class["curved"])}, '
          f'composite {len(red_by_class["composite"])} '
          f'({len(ready_composites)} propagatable), '
          f'mixed {len(red_by_class["mixed"])}, '
          f'empty {len(red_by_class["empty"])} | '
          f'drafts awaiting grade: {len(drafts)}')


if __name__ == '__main__':
    main()
